More cleanup of thread tests.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19113,12 +19113,7 @@ if test "$no_create" != yes; then
 fi
 
 
-#
-# We have to run the thread test here because it is an external program
-# that has to be runable separately for cross-compiling.
-#
-if test "$enable_thread_safety" = yes; then
-if test cross_compiling != yes; then
+# Check for gmake.
 for ac_prog in gmake make
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -19159,41 +19154,54 @@ fi
   test -n "$MAKE" && break
 done
 
-echo "$as_me:$LINENO: checking thread safety of required library functions." >&5
-echo $ECHO_N "checking thread safety of required library functions.... $ECHO_C" >&6
+if ! $MAKE -v | grep 'GNU Make' >/dev/null
+then	rm -f $srcdir/src/Makefile.global
+	echo "$as_me:$LINENO: checking Can not find GNU Make.  It is required." >&5
+echo $ECHO_N "checking Can not find GNU Make.  It is required.... $ECHO_C" >&6
+fi
+
+# Thread testing
+
+# We have to run the thread test here because it is an external program
+# that has to be runable separately for cross-compiling.
+#
+if test "$enable_thread_safety" = yes; then
+if test cross_compiling != yes; then
 #
 # Clean, compile, run, and clean thread test directory.
 # If test fails for any reason, remove Makefile.global so the user can't
 # compile (to simulate a configure failure).
 #
-$MAKE -C $srcdir/src/tools/thread clean >&5 ||
-	( rm -f src/Makefile.global
-	  { { echo "$as_me:$LINENO: error: Can not clean thread test directory." >&5
+echo "$as_me:$LINENO: checking thread safety of required library functions" >&5
+echo $ECHO_N "checking thread safety of required library functions... $ECHO_C" >&6
+if ! $MAKE -C $srcdir/src/tools/thread clean >&5
+then	rm -f $srcdir/src/Makefile.global
+	{ { echo "$as_me:$LINENO: error: Can not clean thread test directory." >&5
 echo "$as_me: error: Can not clean thread test directory." >&2;}
-   { (exit 1); exit 1; }; }) ||
-	exit $?
-$MAKE -C $srcdir/src/tools/thread >&5 ||
-	( rm -f src/Makefile.global
-	  { { echo "$as_me:$LINENO: error: Can not build thread test proram." >&5
+   { (exit 1); exit 1; }; }
+fi
+if ! $MAKE -C $srcdir/src/tools/thread >&5
+then	rm -f $srcdir/src/Makefile.global
+	{ { echo "$as_me:$LINENO: error: Can not build thread test proram." >&5
 echo "$as_me: error: Can not build thread test proram." >&2;}
-   { (exit 1); exit 1; }; }) ||
-	exit $?
-$srcdir/src/tools/thread/thread_test >&5 ||
-	( rm -f src/Makefile.global
-	  echo "no"
-	  echo
-	  $srcdir/src/tools/thread/thread_test
-	  echo
-	  { { echo "$as_me:$LINENO: error: Thread test program failed.  Your platform is not thread-safe." >&5
+   { (exit 1); exit 1; }; }
+fi
+if ! $srcdir/src/tools/thread/thread_test >&5
+then	rm -f $srcdir/src/Makefile.global
+	echo "no"
+	echo
+	$srcdir/src/tools/thread/thread_test
+	echo
+	{ { echo "$as_me:$LINENO: error: Thread test program failed.  Your platform is not thread-safe." >&5
 echo "$as_me: error: Thread test program failed.  Your platform is not thread-safe." >&2;}
-   { (exit 1); exit 1; }; }) ||
-	exit $?
-$MAKE -C $srcdir/src/tools/thread clean >&5 ||
-	( rm -f src/Makefile.global
-	  { { echo "$as_me:$LINENO: error: Can not clean thread test directory." >&5
+   { (exit 1); exit 1; }; }
+fi
+if ! $MAKE -C $srcdir/src/tools/thread clean >&5
+then	rm -f $srcdir/src/Makefile.global
+	{ { echo "$as_me:$LINENO: error: Can not clean thread test directory." >&5
 echo "$as_me: error: Can not clean thread test directory." >&2;}
-   { (exit 1); exit 1; }; }) ||
-	exit $?
+   { (exit 1); exit 1; }; }
+fi
 echo "yes"
 else
 { echo "$as_me:$LINENO: WARNING:
