autoconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5679,6 +5679,72 @@ if test "$ac_cv_search_fdatasync" != no; then
 
 fi
 
+# Cygwin:
+
+echo "$as_me:$LINENO: checking for shmget in -lcygipc" >&5
+echo $ECHO_N "checking for shmget in -lcygipc... $ECHO_C" >&6
+if test "${ac_cv_lib_cygipc_shmget+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcygipc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char shmget ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+shmget ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cygipc_shmget=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_cygipc_shmget=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cygipc_shmget" >&5
+echo "${ECHO_T}$ac_cv_lib_cygipc_shmget" >&6
+if test $ac_cv_lib_cygipc_shmget = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCYGIPC 1
+_ACEOF
+
+  LIBS="-lcygipc $LIBS"
+
+fi
+
 
 if test "$with_readline" = yes; then
 
