Check for gcov and lcov only when coverage testing is enabled.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2484,25 +2484,7 @@ if test "${enable_coverage+set}" = set; then
   enableval=$enable_coverage;
   case $enableval in
     yes)
-      :
-      ;;
-    no)
-      :
-      ;;
-    *)
-      { { echo "$as_me:$LINENO: error: no argument expected for --enable-coverage option" >&5
-echo "$as_me: error: no argument expected for --enable-coverage option" >&2;}
-   { (exit 1); exit 1; }; }
-      ;;
-  esac
-
-else
-  enable_coverage=no
-
-fi
-
-
-for ac_prog in gcov
+      for ac_prog in gcov
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2643,6 +2625,23 @@ if test -z "$GENHTML"; then
 echo "$as_me: error: genhtml not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
+      ;;
+    no)
+      :
+      ;;
+    *)
+      { { echo "$as_me:$LINENO: error: no argument expected for --enable-coverage option" >&5
+echo "$as_me: error: no argument expected for --enable-coverage option" >&2;}
+   { (exit 1); exit 1; }; }
+      ;;
+  esac
+
+else
+  enable_coverage=no
+
+fi
+
+
 
 
 #
