Produce a clean failure in configure when dtrace is selected but cannot be found.  Besides stopping those early who have no dtrace installed whatsoever, this will also alert those who have dtrace in /usr/sbin, which might not be in the path, which would produce confusing failures much later in the build process.
Add documentation about pointing configure to find dtrace.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2004,6 +2004,11 @@ fi
   test -n "$DTRACE" && break
 done
 
+if test -z "$DTRACE"; then
+  { { echo "$as_me:$LINENO: error: dtrace not found" >&5
+echo "$as_me: error: dtrace not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
       ;;
     no)
