Alter the configure script to fail immediately if the C compiler does not provide a working 64-bit integer datatype.  As recently noted, we've been broken on such platforms since early in the 8.4 development cycle.  Since it took nearly two years for anyone to even notice, it seems that the rationale for continuing to support such platforms has reached the point of non-existence.  Rather than thrashing around to try to make it work again, we'll just admit up front that this no longer works.
Back-patch to 8.4 since that branch is also broken.

We should go around to remove INT64_IS_BUSTED support, but just in HEAD,
so that seems like material for a separate commit.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20800,6 +20800,7 @@ fi
 
 
 
+
 { echo "$as_me:$LINENO: checking whether long int is 64 bits" >&5
 echo $ECHO_N "checking whether long int is 64 bits... $ECHO_C" >&6; }
 if test "${pgac_cv_type_long_int_64+set}" = set; then
@@ -21064,6 +21065,11 @@ _ACEOF
 
 fi
 
+  if test x"$HAVE_LONG_LONG_INT_64" = x"no" ; then
+    { { echo "$as_me:$LINENO: error: Cannot find a working 64-bit integer type." >&5
+echo "$as_me: error: Cannot find a working 64-bit integer type." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 fi
 
 
@@ -25064,26 +25070,6 @@ _ACEOF
 
 fi
 
-
-
-# If the user did not disable integer datetimes, check that
-# there is a working 64-bit integral type to use.
-if test x"$USE_INTEGER_DATETIMES" = x"yes" &&
-   test x"$HAVE_LONG_INT_64" = x"no" &&
-   test x"$HAVE_LONG_LONG_INT_64" = x"no" &&
-   test x"$HAVE_INT64" = x"no" ; then
-  { { echo "$as_me:$LINENO: error:
-Integer-based datetime support requires a 64-bit integer type,
-but no such type could be found. The --disable-integer-datetimes
-configure option can be used to disable integer-based storage
-of datetime values." >&5
-echo "$as_me: error:
-Integer-based datetime support requires a 64-bit integer type,
-but no such type could be found. The --disable-integer-datetimes
-configure option can be used to disable integer-based storage
-of datetime values." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 
 if test "$PORTNAME" != "win32"
