Add mention to check config.log if thread test failure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19174,8 +19174,8 @@ echo "$as_me: error: Can not build thread test proram." >&2;}
    { (exit 1); exit 1; }; })
 $srcdir/src/tools/thread/thread_test >&5 ||
 	( rm -f src/Makefile.global
-	  { { echo "$as_me:$LINENO: error: Thread test program failed." >&5
-echo "$as_me: error: Thread test program failed." >&2;}
+	  { { echo "$as_me:$LINENO: error: Thread test program failed.  See 'config.log' for details." >&5
+echo "$as_me: error: Thread test program failed.  See 'config.log' for details." >&2;}
    { (exit 1); exit 1; }; })
 $MAKE -C $srcdir/src/tools/thread clean >&5 ||
 	( rm -f src/Makefile.global
