Improve error message for platform thread failure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19172,8 +19172,9 @@ echo "$as_me: error: Can not build thread test proram." >&2;}
    { (exit 1); exit 1; }; })
 $srcdir/src/tools/thread/thread_test >&5 ||
 	( rm -f src/Makefile.global
-	  { { echo "$as_me:$LINENO: error: Thread test program failed.  See 'config.log' for details." >&5
-echo "$as_me: error: Thread test program failed.  See 'config.log' for details." >&2;}
+	  $srcdir/src/tools/thread/thread_test
+	  { { echo "$as_me:$LINENO: error: Thread test program failed.  Your platform is not thread-safe." >&5
+echo "$as_me: error: Thread test program failed.  Your platform is not thread-safe." >&2;}
    { (exit 1); exit 1; }; })
 $MAKE -C $srcdir/src/tools/thread clean >&5 ||
 	( rm -f src/Makefile.global
