Fix omission of -X (--no-psqlrc) in some psql invocations.
As of commit d5563d7df, psql -c no longer implies -X, but not all of
our regression testing scripts had gotten that memo.

To ensure consistency of results across different developers, make
sure that *all* invocations of psql in all scripts in our tree
use -X, even where this is not what previously happened.

Michael Paquier and Tom Lane

diff --git a/src/test/locale/koi8-r/runall b/src/test/locale/koi8-r/runall
--- a/src/test/locale/koi8-r/runall
+++ b/src/test/locale/koi8-r/runall
@@ -38,12 +38,12 @@ for f in char varchar text; do
 
    dropdb testlocale >/dev/null 2>&1
    createdb testlocale || abort "createdb failed"
-   psql -d testlocale -c "CREATE TABLE usastates (abbrev char(2), name_en char(20), name_ru $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
-   psql testlocale < test-koi8.sql.in > test-koi8-$f.sql.out 2>/dev/null || abort "test query failed"
+   psql -X -d testlocale -c "CREATE TABLE usastates (abbrev char(2), name_en char(20), name_ru $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
+   psql -X testlocale < test-koi8.sql.in > test-koi8-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-koi8-$f.sql.out test-koi8-$f.sql.out
 done
 echo "Testing PgSQL: select on regexp..."
-psql testlocale < test-koi8-select.sql.in > test-koi8-select.sql.out 2>/dev/null || abort "select query failed"
+psql -X testlocale < test-koi8-select.sql.in > test-koi8-select.sql.out 2>/dev/null || abort "select query failed"
 diff expected/test-koi8-select.sql.out test-koi8-select.sql.out
 dropdb testlocale || abort "dropdb failed"
 echo "Finished."
