Solaris has always had problems with 1947 in the regression tests so I prepared a set of expected files to make things look OK.
There's also a file to account for minor variations
in the geopmetry output and a resultmap patch to
pull them all together.

With these changes PostgreSQL, from CVS, builds and
regression tests (runcheck) cleanly.

Keith Parks.

diff --git a/src/test/locale/koi8-r/runall b/src/test/locale/koi8-r/runall
--- a/src/test/locale/koi8-r/runall
+++ b/src/test/locale/koi8-r/runall
@@ -39,7 +39,7 @@ for f in char varchar text; do
    fi
    echo "Testing PgSQL: sort on $ftype type..."
 
-   destroydb testlocale >/dev/null 2>&1
+   dropdb testlocale >/dev/null 2>&1
    createdb testlocale || abort "createdb failed"
    psql -d testlocale -c "CREATE TABLE usastates (abbrev char(2), name_en char(20), name_ru $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
    psql testlocale < test-koi8.sql.in > test-koi8-$f.sql.out 2>/dev/null || abort "test query failed"
@@ -48,5 +48,5 @@ done
 echo "Testing PgSQL: select on regexp..."
 psql testlocale < test-koi8-select.sql.in > test-koi8-select.sql.out 2>/dev/null || abort "select query failed"
 diff expected/test-koi8-select.sql.out test-koi8-select.sql.out
-destroydb testlocale || abort "destroydb failed"
+dropdb testlocale || abort "dropdb failed"
 echo "Finished."
