End of the make file simplifications.

diff --git a/src/test/bench/Makefile b/src/test/bench/Makefile
--- a/src/test/bench/Makefile
+++ b/src/test/bench/Makefile
@@ -7,56 +7,52 @@
 #
 #
 # IDENTIFICATION
-#    $Header: /cvsroot/pgsql/src/test/bench/Attic/Makefile,v 1.1.1.1 1996/07/09 06:22:21 scrappy Exp $
+#    $Header: /cvsroot/pgsql/src/test/bench/Attic/Makefile,v 1.2 1996/11/12 11:42:49 bryanh Exp $
 #
 #-------------------------------------------------------------------------
 
-MKDIR=	../../mk
-include $(MKDIR)/postgres.mk
-
+SRCDIR= ../..
+LIBPQDIR= $(SRCDIR)/libpq
+include ../../Makefile.global
 
 CREATEFILES= create.sql bench.sql
-
-include $(MKDIR)/postgres.user.mk
-
-
 OUTFILES= bench.out bench.out.perquery
-CLEANFILES+= $(CREATEFILES) $(OUTFILES)
+
+CFLAGS+= -I$(LIBPQDIR) $(CFLAGS_SL)
+
+all: $(CREATEFILES)
+	rm -f $(OUTFILES)
+
+create.sql: create.source
+	if [ -z "$$USER" ]; then USER=$$LOGNAME; fi; \
+	if [ -z "$$USER" ]; then USER=`whoami`; fi; \
+	if [ -z "$$USER" ]; then echo 'Cannot deduce $$USER.'; exit 1; fi; \
+	rm -f $@; \
+	C=`pwd`; \
+	sed -e "s:_CWD_:$$C:g" \
+	    -e "s:_OBJWD_:$$C:g" \
+	    -e "s:_SLSUFF_:$(SLSUFF):g" \
+	    -e "s/_USER_/$$USER/g" < $< > $@
 
 bench.sql: 
-	cat > $(objdir)/$@ < /dev/null
 	x=1; \
 	for i in `ls query[0-9][0-9]`; do \
-		echo "select $$x as x" >> $(objdir)/$@; \
-		cat $$i >> $(objdir)/$@; \
-		x=`expr $$x + 1`; \
+	  echo "select $$x as x" >> bench.sql; \
+	  cat $$i >> bench.sql; \
+	  x=`expr $$x + 1`; \
 	done
 
-bench2.pq: 
-	cat > ${.TARGET} < /dev/null
-	C=`pwd`; cd ${.CURDIR}; \
-	for i in 1 2 3 4 5 6; do \
-		echo "select timeofday();" >> $$C/${.TARGET}; \
-	done; \
-	x=1; \
-	for i in `ls query[0-9][0-9]`; do \
-		echo "select $$x as x;" >> $$C/${.TARGET}; \
-		echo "select timeofday();" >> $$C/${.TARGET}; \
-		cat $$i >> $$C/${.TARGET}; \
-		echo "select timeofday();" >> $$C/${.TARGET}; \
-		x=`expr $$x + 1`; \
-	done
+runtest: $(OUTFILES)
 
 bench.out: $(CREATEFILES)
 	$(SHELL) ./create.sh && \
-	$(SHELL) ./runwisc.sh > $(objdir)/$@ 2>&1
-	@echo "RESULTS OF BENCHMARK ARE SAVED IN ${MAKEOBJDIR}/bench.out";
+	$(SHELL) ./runwisc.sh >bench.out 2>&1
+	@echo "RESULTS OF BENCHMARK ARE SAVED IN FILE bench.out";
 
 bench.out.perquery: bench.out
-	$(SHELL) ./perquery < $(objdir)/bench.out 2>&1 > $@
-	@echo "BREAKDOWN OF BENCHMARK IS SAVED IN ${MAKEOBJDIR}/bench.out.perquery";
+	$(SHELL) ./perquery <bench.out 2>&1 > $@
+	@echo "BREAKDOWN OF BENCHMARK IS SAVED IN FILE" \
+	  "bench.out.perquery";
 
-all:: $(CREATEFILES)
-	rm -f $(OUTFILES)
-
-runtest: ${OUTFILES}
+clean:
+	rm -f $(OUTFILES) $(CREATEFILES)
diff --git a/src/test/regress/Makefile b/src/test/regress/Makefile
--- a/src/test/regress/Makefile
+++ b/src/test/regress/Makefile
@@ -7,74 +7,85 @@
 #
 #
 # IDENTIFICATION
-#    $Header: /cvsroot/pgsql/src/test/regress/Makefile,v 1.7 1996/11/12 11:16:44 scrappy Exp $
+#    $Header: /cvsroot/pgsql/src/test/regress/Makefile,v 1.8 1996/11/12 11:43:05 bryanh Exp $
 #
 #-------------------------------------------------------------------------
 
-MKDIR=	../../mk
-include $(MKDIR)/postgres.mk
-include $(MKDIR)/postgres.user.mk
+SRCDIR= ../..
+LIBPQDIR= $(SRCDIR)/libpq
+include ../../Makefile.global
 
-CFLAGS+=-I../../include
+CFLAGS+= -I$(LIBPQDIR) -I../../include
 
+LDADD+= -L$(LIBPQDIR) -lpq
+        
 #
-# try locating libpq.a in the following places
-#
-LIBPQ:=  -L$(srcdir)/libpq/$(objdir) -L$(LIBDIR) -lpq
-
-LDADD+= $(LIBPQ)
-
-
-#
-# build dynamically-loaded object files
+# DLOBJS is the dynamically-loaded object file.  The regression test uses 
+# this when it does a CREATE FUNCTION ... LANGUAGE 'C').
 #
 DLOBJS= regress$(SLSUFF)
 
 #
 # ... plus test query inputs
 #
-CREATEFILES= $(DLOBJS:%=$(objdir)/%) \
-	create.sql queries.sql errors.sql destroy.sql security.sql expected.out
+# INFILES is the files the regression test uses for input.
+INFILES= $(DLOBJS) \
+         create.sql queries.sql errors.sql destroy.sql security.sql \
+         expected.out
+#
+# plus exports files
+#
+ifdef EXPSUFF
+INFILES+= $(DLOBJS:.o=$(EXPSUFF))
+endif
 
-
+# OUTFILES is the files that get created by running the regression test.
 OUTFILES= stud_emp.data onek.data regress.out aportal.out
-
-CLEANFILES+= $(notdir $(CREATEFILES)) $(OUTFILES)
-
-$(OUTFILES): $(CREATEFILES)
-	$(SHELL) ./regress.sh 2>&1 | tee $(objdir)/regress.out
-	@echo "RESULTS OF REGRESSION ARE SAVED IN $(objdir)/regress.out"
-
-#
-# expected results file -- expand macros for user and location
-#
-# the expected.input file is make by hand from 'regress.out' when the
-# regression test has been updated and a successful output obtained
-#
-expected.out: expected.input
-	if [ -z "$$USER" ]; then USER=$$LOGNAME; fi; \
-	if [ -z "$$USER" ]; then USER=`whoami`; fi; \
-	if [ -z "$$USER" ]; then echo 'Cannot deduce $USER.'; exit 1; fi; \
-	rm -f $(objdir)/expected.out; \
-	C="`pwd`"; \
-	sed -e "s:_CWD_:$$C:g" \
-	    -e "s:_OBJWD_:$$C/$(objdir):g" \
-            -e "s:_SLSUFF_:$(SLSUFF):g" \
-	    -e "s/_USER_/$$USER/g" < expected.input > $(objdir)/expected.out
 
 #
 # prepare to run the test (including clean-up after the last run)
 #
-all:: $(CREATEFILES)
-	cd $(objdir); rm -f $(OUTFILES)
+all: $(INFILES)
+	rm -f $(OUTFILES)
 
 #
 # run the test
 #
-runtest: expected.out regress.out
+runtest: $(INFILES) expected.out 
+	$(SHELL) ./regress.sh 2>&1 | tee regress.out
+	@echo "ACTUAL RESULTS OF REGRESSION TEST ARE NOW IN FILE regress.out"
 
-#
-# installation
-#
-install: localobj all
+# The expected.input file is part of the distribution.  It was made by hand
+# from 'regress.out' from a reference run of the regression test, replacing
+# installation-dependent things with names like _CWD_.  The following rule
+# turns those names back into real values for the instant installation to
+# create a standard (expected.out) against which to compare regress.out 
+# from the experimental run.
+
+expected.out: expected.input
+	if [ -z "$$USER" ]; then USER=$$LOGNAME; fi; \
+	if [ -z "$$USER" ]; then USER=`whoami`; fi; \
+	if [ -z "$$USER" ]; then echo 'Cannot deduce $USER.'; exit 1; fi; \
+	rm -f expected.out; \
+	C="`pwd`"; \
+	sed -e "s:_CWD_:$$C:g" \
+	    -e "s:_OBJWD_:$$C:g" \
+            -e "s:_SLSUFF_:$(SLSUFF):g" \
+	    -e "s/_USER_/$$USER/g" < expected.input > expected.out
+	@echo "YOUR EXPECTED RESULTS ARE NOW IN FILE expected.out."
+
+%.sql: %.source
+	if [ -z "$$USER" ]; then USER=$$LOGNAME; fi; \
+	if [ -z "$$USER" ]; then USER=`whoami`; fi; \
+	if [ -z "$$USER" ]; then echo 'Cannot deduce $$USER.'; exit 1; fi; \
+	rm -f $@; \
+	C=`pwd`; \
+	sed -e "s:_CWD_:$$C:g" \
+	    -e "s:_OBJWD_:$$C:g" \
+	    -e "s:_SLSUFF_:$(SLSUFF):g" \
+	    -e "s/_USER_/$$USER/g" < $< > $@
+
+clean:
+	rm -f $(INFILES)
+	rm -f $(OUTFILES)
 
diff --git a/src/tutorial/Makefile b/src/tutorial/Makefile
--- a/src/tutorial/Makefile
+++ b/src/tutorial/Makefile
@@ -1,39 +1,55 @@
 #-------------------------------------------------------------------------
 #
 # Makefile--
-#    Makefile for tutorial/C-code
-#
-# Copyright (c) 1994, Regents of the University of California
-#
+#    Makefile for tutorial
 #
 # IDENTIFICATION
-#    $Header: /cvsroot/pgsql/src/tutorial/Makefile,v 1.1.1.1 1996/07/09 06:22:33 scrappy Exp $
+#    $Header: /cvsroot/pgsql/src/tutorial/Makefile,v 1.2 1996/11/12 11:43:20 bryanh Exp $
 #
 #-------------------------------------------------------------------------
 
-MKDIR=	../mk
-include $(MKDIR)/postgres.mk
+SRCDIR= ..
+LIBPQDIR= $(SRCDIR)/libpq
+include ../Makefile.global
 
-VPATH:= $(VPATH):C-code
+CFLAGS+= -I$(LIBPQDIR) -I../../include
 
+LDADD+= -L$(LIBPQDIR) -lpq
+        
 #
-# build dynamically-loaded object files
+# DLOBJS is the dynamically-loaded object files.  The "funcs" queries
+# include CREATE FUNCTIONs that load routines from these files.
 #
-DLOBJS= complex$(SLSUFF) funcs$(SLSUFF) 
+DLOBJS= complex$(SLSUFF) funcs$(SLSUFF)
 
+QUERIES= advanced.sql basics.sql complex.sql funcs.sql syscat.sql
 #
-# ... plus test query inputs
+# plus exports files
 #
-CREATEFILES= $(DLOBJS:%=$(objdir)/%) \
-	advanced.sql basics.sql complex.sql funcs.sql syscat.sql
+ifdef EXPSUFF
+DLOBJS+= $(DLOBJS:.o=$(EXPSUFF))
+endif
 
-include $(MKDIR)/postgres.user.mk
+all: $(QUERIES)
 
-CFLAGS+= -I$(srcdir)/backend
+%.sql: %.source
+	if [ -z "$$USER" ]; then USER=$$LOGNAME; fi; \
+	if [ -z "$$USER" ]; then USER=`whoami`; fi; \
+	if [ -z "$$USER" ]; then echo 'Cannot deduce $$USER.'; exit 1; fi; \
+	rm -f $@; \
+	C=`pwd`; \
+	sed -e "s:_CWD_:$$C:g" \
+	    -e "s:_OBJWD_:$$C:g" \
+	    -e "s:_SLSUFF_:$(SLSUFF):g" \
+	    -e "s/_USER_/$$USER/g" < $< > $@
 
-CLEANFILES+= $(notdir $(CREATEFILES))
+funcs.sql:: $(DLOBJS)
 
-all:: $(CREATEFILES)
+$(DLOBJS): 
+	$(MAKE) -C C-code $@
+	cp C-code/$@ .
 
-
-
+clean:
+	$(MAKE) -C C-code clean
+	rm -f $(QUERIES)
+	rm -f $(DLOBJS)
