Modify pgrminclude -v to report include files that can't be compiled on their own.
Avoid compile problems with defines being redefined after the removal of
the #if blocks.

Change script to use shell functions for simplicity.

diff --git a/src/tools/pginclude/pgrminclude b/src/tools/pginclude/pgrminclude
--- a/src/tools/pginclude/pgrminclude
+++ b/src/tools/pginclude/pgrminclude
@@ -7,21 +7,22 @@ then	echo "pgdefine must be in your PATH" 1>&2
 fi
 
 trap "rm -f /tmp/$$.c /tmp/$$.o /tmp/$$ /tmp/$$a /tmp/$$b" 0 1 2 3 15
-# do include files first
-(find . \( -name .git -a -prune \) -o -type f -name '*.h' -print;
- find . \( -name .git -a -prune \) -o -type f -name '*.c' -print ) |
-grep -v '\./postgres.h' |
-grep -v '\./postgres_fe.h' |
-grep -v '\./pg_config.h' |
-grep -v '\./c.h' |
-while read FILE
-do
-	if [ `expr $FILE : '.*\.h$'` -ne 0 ]
-	then	IS_INCLUDE="Y"
-	else	IS_INCLUDE="N"
-	fi
 
-	# loop through all includes
+if [ "$1" = "-v" ]
+then	VERBOSE="Y"
+else	VERBOSE=""
+fi
+
+verbose_output() {
+	if [ "$VERBOSE" ]
+	then	cat /tmp/$$
+		cat /tmp/$$b
+		nl /tmp/$$.c
+	fi
+}
+
+process_includes_in_file() {
+	# loop through all includes mentioned in the file
 	cat "$FILE" | 
 	grep "^#include\>" |
 	grep -v '/\* *pgrminclude  *ignore *\*/' |
@@ -29,65 +30,97 @@ do
 	grep -v 'parser/kwlist\.h' |
 	grep -v '\.c$' |
 	while read INCLUDE
-	do
-		if [ "$1" = "-v" ]
+	do	if [ "$VERBOSE" ]
 		then	echo "checking $FILE $INCLUDE"
 		fi
-
-		[ -s /usr/include/$INCLUDE ] && continue
-		[ "$INCLUDE" = postgres.h ] && continue
-		[ "$INCLUDE" = postgres_fe.h ] && continue
-		[ "$INCLUDE" = pg_config.h ] && continue
-		[ "$INCLUDE" = c.h ] && continue
-
-		# preserve configure-specific includes
-		# these includes are surrounded by #ifdef's
-		grep -B1 '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' "$FILE" |
-		     egrep -q '^#if|^#else|^#elif' && continue
-		grep -A1 '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' "$FILE" |
-		     egrep -q '^#else|^#elif|^#endif' && continue
-
-	        # Remove all #if and #ifdef blocks because the blocks
-      		# might contain code that is not compiled on this platform.
-		cat "$FILE" |
-		grep -v "^#if" |
-		grep -v "^#else" |
-		grep -v "^#elif" |
-		grep -v "^#endif" >/tmp/$$a
-
-		# set up initial file contents
-		grep -v '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' \
-			/tmp/$$a >/tmp/$$b
-
-		if [ "$IS_INCLUDE" = "Y" ]
-		then	echo "#include \"postgres.h\"" >/tmp/$$.c
-		else	>/tmp/$$.c
-		fi
-
-		echo "#include \"/tmp/$$b\"" >>/tmp/$$.c
-		echo "void include_test(void);" >>/tmp/$$.c
-		echo "void include_test() {" >>/tmp/$$.c
-		if [ "$IS_INCLUDE" = "Y" ]
-		then	pgdefine "$FILE" >>/tmp/$$.c
-		fi
-		echo "}" >>/tmp/$$.c
-
-		# Use -O1 to get warnings only generated by optimization,
-		# but -O2 is too slow.
-		cc -fsyntax-only -Werror -Wall -Wmissing-prototypes \
-			-Wmissing-declarations -I/pg/include -I/pg/backend \
-			-I/pg/interfaces/libpq -I`dirname $FILE` $CFLAGS -O1 -c /tmp/$$.c \
-			-o /tmp/$$.o >/tmp/$$ 2>&1
-		if [ "$?" -eq 0 ]
-		then	echo "$FILE $INCLUDE"
-			if [ "$1" = "-v" ]
-			then	cat /tmp/$$
-				cat /tmp/$$b
-				cat /tmp/$$.c
-			fi
-			grep -v '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' \
-				"$FILE" >/tmp/$$b
-			mv /tmp/$$b "$FILE"
-		fi
+		compile_file
 	done
+}
+
+compile_file() {
+	[ "$INCLUDE" -a -s /usr/include/"$INCLUDE" ] && continue
+	[ "$INCLUDE" = "postgres.h" ] && continue
+	[ "$INCLUDE" = "postgres_fe.h" ] && continue
+	[ "$INCLUDE" = "pg_config.h" ] && continue
+	[ "$INCLUDE" = "c.h" ] && continue
+
+	# preserve configure-specific includes
+	# these includes are surrounded by #ifdef's
+	grep -B1 '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' "$FILE" |
+	     egrep -q '^#if|^#else|^#elif' && continue
+	grep -A1 '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' "$FILE" |
+	     egrep -q '^#else|^#elif|^#endif' && continue
+
+        # Remove all #if and #ifdef blocks because the blocks
+	# might contain code that is not compiled on this platform.
+	cat "$FILE" |
+	grep -v "^#if" |
+	grep -v "^#else" |
+	grep -v "^#elif" |
+	grep -v "^#endif" |
+	# with #if blocks gone, now undef #defines to avoid redefine 
+	# warning and failure
+	sed 's/#define[ 	][ 	]*\([A-Za-z0-9_]*\).*$/#undef \1\n&/' >/tmp/$$a
+
+	# set up initial file contents
+	grep -v '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' \
+		/tmp/$$a >/tmp/$$b
+
+	if [ "$IS_INCLUDE" = "Y" ]
+	then	echo "#include \"postgres.h\"" >/tmp/$$.c
+	else	>/tmp/$$.c
+	fi
+
+	echo "#include \"/tmp/$$b\"" >>/tmp/$$.c
+	# supress fcinfo errors
+	echo "#undef PG_GETARG_DATUM" >>/tmp/$$.c
+	echo "#define PG_GETARG_DATUM(n)" >>/tmp/$$.c
+	echo "void include_test(void);" >>/tmp/$$.c
+	echo "void include_test() {" >>/tmp/$$.c
+	if [ "$IS_INCLUDE" = "Y" ]
+	then	pgdefine "$FILE" >>/tmp/$$.c
+	fi
+	echo "}" >>/tmp/$$.c
+
+	# Use -O1 to get warnings only generated by optimization,
+	# but -O2 is too slow.
+	cc -fsyntax-only -Werror -Wall -Wmissing-prototypes \
+		-Wmissing-declarations -I/pg/include -I/pg/backend \
+		-I/pg/interfaces/libpq -I`dirname $FILE` $CFLAGS -O1 -c /tmp/$$.c \
+		-o /tmp/$$.o >/tmp/$$ 2>&1
+	if [ "$?" -eq 0 ]
+	then	[ "$INCLUDE" -o "$VERBOSE" ] && echo "$FILE $INCLUDE"
+		grep -v '^#include[ 	][ 	]*[<"]'"$INCLUDE"'[>"]' \
+			"$FILE" >/tmp/$$b
+		mv /tmp/$$b "$FILE"
+		return 0
+	else	return 1
+	fi
+}
+
+# Process include files first because they can affect the compilation 
+# of *.c files.
+(find . \( -name .git -a -prune \) -o -type f -name '*.h' -print;
+ find . \( -name .git -a -prune \) -o -type f -name '*.c' -print ) |
+grep -v '/postgres.h$' |
+grep -v '/postgres_fe.h$' |
+grep -v '/pg_config.h$' |
+grep -v '\./c.h$' |
+while read FILE
+do
+	if [ `expr $FILE : '.*\.h$'` -ne 0 ]
+	then	IS_INCLUDE="Y"
+	else	IS_INCLUDE="N"
+	fi
+
+	# Can we compile the file with all existing includes?
+	INCLUDE=""
+	compile_file
+	# If the file can't be compiled on its own, there is no sense
+	# trying to remove the include files.
+	if [ "$?" -ne 0 ]
+	then	echo "cannot compile $FILE with existing includes"
+		verbose_output
+	else	process_includes_in_file
+	fi
 done
