Allow --with-mb=SQL_ASCII

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -858,11 +858,11 @@ if test "${with_mb+set}" = set; then
   withval="$with_mb"
   
 	case "$withval" in
-	EUC_JP|EUC_CN|EUC_KR|EUC_TW|UNICODE|MULE_INTERNAL|LATIN1|LATIN2|LATIN3|LATIN4|LATIN5|KOI8|WIN|ALT)
+	SQL_ASCII|EUC_JP|EUC_CN|EUC_KR|EUC_TW|UNICODE|MULE_INTERNAL|LATIN1|LATIN2|LATIN3|LATIN4|LATIN5|KOI8|WIN|ALT)
 	    echo "$ac_t"""enabled with $withval"" 1>&6
             ;;
 	*)
-	    { echo "configure: error: *** You must supply an argument to the --with-mb option one of EUC_JP,EUC_CN,EUC_KR,EUC_TW,UNICODE,MULE_INTERNAL,LATIN1-5,KOI8,WIN,ALT" 1>&2; exit 1; }
+	    { echo "configure: error: *** You must supply an argument to the --with-mb option one of SQL_ASCII,EUC_JP,EUC_CN,EUC_KR,EUC_TW,UNICODE,MULE_INTERNAL,LATIN1-5,KOI8,WIN,ALT" 1>&2; exit 1; }
 	  ;;
 	esac
 	MULTIBYTE="$withval"
