Adjust pgtest coding to be less complex.

diff --git a/src/tools/pgtest b/src/tools/pgtest
--- a/src/tools/pgtest
+++ b/src/tools/pgtest
@@ -20,19 +20,20 @@ TMP="/tmp/$$"
 
 [ "X$1" != "X-n" ] && PGCLEAN=clean
 
-# run make check, capture return code in $TMP/ret, then display
-# that but capture it in $TMP/0 too, and return original make
-# error code.  If that succeded, display captured warnings
+# Run "make check" and store return code in $TMP/ret.
+# Display output but also capture it in $TMP/0.
+($MAKE $PGCLEAN check 2>&1; echo "$?" > $TMP/ret) | tee  $TMP/0
 
-($MAKE $PGCLEAN check 2>&1; echo "$?" > $TMP/ret) |
-	(tee  $TMP/0; exit `cat $TMP/ret`) &&
-cat $TMP/0 |
-# The following grep's have to be adjusted for your setup because
-# certain warnings are acceptable.
-grep -i warning |
-grep -v setproctitle |
-grep -v find_rule |
-grep -v yy_flex_realloc
+# If success, display warnings
+if [ $(cat $TMP/ret) -eq 0 ]
+then	cat $TMP/0 |
+	# The following grep's have to be adjusted for your setup because
+	# certain warnings are acceptable.
+	grep -i warning |
+	grep -v setproctitle |
+	grep -v find_rule |
+	grep -v yy_flex_realloc
+fi
 
 # return original make error code
 exit `cat $TMP/ret`
